apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: root
  JWT_SECRET_KEY: 173c7faaf30859adad7375b1b3dd8133ea35c673645d0b33b3b301e7bc5283ba