FROM node:22-alpine AS build
WORKDIR /app
COPY /frontend/package*.json ./
RUN npm ci
COPY frontend .
RUN npm run build --configuration=production

FROM nginx:alpine
COPY --from=build /app/dist/client/browser /usr/share/nginx/html
COPY nginx-k8s.conf /etc/nginx/conf.d/default.conf
EXPOSE 80