minio:
  endpoint: http://192.168.100.206:9000
  access-key: root
  secret-key: rootpasswd
  bucket-name: media-gallery

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/main_db
    username: postgres
    password: root

security:
  jwt:
    secret-key: 173c7faaf30859adad7375b1b3dd8133ea35c673645d0b33b3b301e7bc5283ba
    expiration-time: 3600000